version: '3'

services:
  web_vue:
    build: .
    image: vue:0.0.1
    container_name: vue
    volumes:
      - ./app:/app
    command: sh -c "npm install --force && npm run $function"
#    restart: always
    networks:
      - default
    ports:
      - 8080:8080
